data:
    dataset: "Market1501"  # 데이터셋 이름을 Market1501로 변경
    data_dir: "/workspace/Market-1501"  # 데이터셋 디렉토리 경로 설정
    data_path: "/workspace/Market-1501"
    image_size: [256,256]
    channels: 3  # 동일하게 사용됨
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4  # 데이터 로더에서 사용될 워커 수

model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 64
    n_epochs: 1000
    n_iters: 50000
    snapshot_freq: 5000
    validation_freq: 2000

sampling:
    batch_size: 64
    last_only: True

optim:
    weight_decay: 0.00001
    optimizer: "Adam"
    lr: 0.0001
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
